repositories:
  - name: cilium
    url: https://helm.cilium.io/
  - name: coredns
    url: https://coredns.github.io/helm
  - name: nfs-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    values:
      - kubeProxyReplacement: true
        k8sServiceHost: kubegate
        k8sServicePort: 6443
        cgroup:
          automount:
            enabled: false
          hostRoot: /sys/fs/cgroup
  - name: coredns
    namespace: kube-system
    chart: coredns/coredns
    values:
      - service:
          clusterIP: 10.32.0.10
        replicaCount: 2    
  - name: nfs-provisioner
    namespace: kube-system
    chart: nfs-provisioner/nfs-subdir-external-provisioner
    values:
      - nfs:
          server: 192.168.64.1
          path: /Users/rjghik/kubenet/nfs-pvs
        storageClass:
          defaultClass: true  
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
  - name: redis
    namespace: default
    chart: oci://registry-1.docker.io/bitnamicharts/redis
    version: 17.13.2
    needs: [kube-system/coredns, kube-system/nfs-provisioner]
    values:
      - master:
          service:
            type: LoadBalancer
        replica:
          replicaCount: 2

